In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("DataJKT.csv")
dataset

,tahun,nama_provinsi,nama_kabupaten/kota,nama_kecamatan,nama_kelurahan,jumlah_rt,jumlah_rw
0,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. PANGGANG,29,5
1,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. KELAPA,31,5
2,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU UTR,P. HARAPAN,15,3
3,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU SLT,P. UNTUNG JAWA,9,3
4,2013,PROVINSI DKI JAKARTA,KAB.ADM.KEP.SERIBU,KEP. SERIBU SLT,P. TIDUNG,29,4
...,...,...,...,...,...,...,...
262,2013,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,MUNJUL,75,8
263,2013,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,SETU,44,6
264,2013,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,BAMBU APUS,65,5
265,2013,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,LUBANG BUAYA,113,12
266,2013,PROVINSI DKI JAKARTA,JAKARTA TIMUR,CIPAYUNG,CEGER,39,5

In [3]:
dataset = pd.read_csv('DataJKT.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. PANGGANG' 29]
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. KELAPA' 31]
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU UTR'
  'P. HARAPAN' 15]
 ...
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'BAMBU APUS' 65]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'LUBANG BUAYA'
  113]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'CEGER' 39]]

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
print(x_train)

[[2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'TAMBORA' 'JEMBATAN BESI'
  100]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'KEBAYORAN BARU' 'PULO'
  47]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'DUREN SAWIT' 'PONDOK KOPI'
  107]
 ...
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'KEBON JERUK' 'DURI KEPA'
  137]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'JOHAR BARU' 'KAMPUNG RAWA'
  104]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'CILANDAK' 'PONDOK LABU'
  98]]

In [7]:
print(x_test)

[[2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'KEBAYORAN BARU'
  'SENAYAN' 24]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'CILINCING' 'ROROTAN' 136]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'PULO GADUNG' 'JATI' 137]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'GAMBIR' 'PETOJO UTARA' 101]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'PONDOK RANGGON'
  63]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CAKUNG' 'RAWA TERATE' 60]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'TAMAN SARI' 'MAPHAR' 98]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'GROGOL PETAMBURAN'
  'JELAMBAR BARU' 133]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PESANGGRAHAN' 'ULUJAMI'
  95]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'TANAH ABANG'
  'KAMPUNG BALI' 81]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'MAKASAR' 'PINANG RANTI' 54]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'TANJUNG PRIOK'
  'KEBON BAWANG' 196]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PASAR MINGGU' 'RAGUNAN'
  108]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'MAMPANG PRAPATAN'
  'PELA MAMPANG' 157]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'PULO GADUNG'
  'PISANGAN TIMUR' 166]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'SAWAH BESAR'
  'GUNUNG SAHARI UTARA' 99]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'SETIA BUDI'
  'KARET KUNINGAN' 75]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PASAR MINGGU'
  'PEJATEN TIMUR' 146]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'MAMPANG PRAPATAN'
  'MAMPANG PRAPATAN' 74]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'TANJUNG PRIOK'
  'TANJUNG PRIOK' 158]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PESANGGRAHAN'
  'PETUKANGAN UTARA' 122]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'MATRAMAN' 'KEBON MANGGIS'
  64]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'JATINEGARA'
  'CIPINANG BESAR SELATAN' 128]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'GAMBIR' 'CIDENG' 114]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'KEMBANGAN' 'JOGLO' 114]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'KALI DERES' 'PEGADUNGAN'
  183]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'TAMBORA' 'PEKOJAN' 144]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'MAKASAR' 'MAKASAR' 94]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'MAMPANG PRAPATAN'
  'BANGKA' 66]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'DUREN SAWIT' 'MALAKA SARI'
  140]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'KEMBANGAN'
  'KEMBANGAN SELATAN' 77]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'PASAR REBO' 'KALISARI' 102]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'DUREN SAWIT'
  'PONDOK KELAPA' 166]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'TAMAN SARI' 'PINANGSIA' 57]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'SENEN' 'PASEBAN' 115]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'TAMBORA' 'ANGKE' 139]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'PULO GADUNG' 'CIPINANG'
  183]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'MENTENG' 'GONDANGDIA' 40]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'DUREN SAWIT' 'KLENDER' 200]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'KEMAYORAN' 'SERDANG' 113]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'KEBAYORAN BARU'
  'CIPETE UTARA' 105]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'JATINEGARA'
  'CIPINANG BESAR UTARA' 192]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'PADEMANGAN'
  'PADEMANGAN BARAT' 213]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'CIPAYUNG' 'CIPAYUNG' 59]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'KEBAYORAN BARU'
  'PETOGOGAN' 76]
 [2013 'PROVINSI DKI JAKARTA' 'KAB.ADM.KEP.SERIBU' 'KEP. SERIBU SLT'
  'P. PARI' 14]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'KEMAYORAN' 'CEMPAKA BARU'
  138]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PANCORAN' 'CIKOKO' 42]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'KOJA' 'LAGOA' 222]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA PUSAT' 'SAWAH BESAR' 'PASAR BARU'
  76]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA BARAT' 'KEBON JERUK' 'KELAPA DUA'
  60]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA SELATAN' 'PESANGGRAHAN'
  'PETUKANGAN SELATAN' 86]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA UTARA' 'KOJA' 'TUGU UTARA' 214]
 [2013 'PROVINSI DKI JAKARTA' 'JAKARTA TIMUR' 'PASAR REBO' 'PEKAYON' 116]]

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'PROVINSI DKI JAKARTA'